### ISSUE TITLE
Failed to retrieve signing url in case the signingUrls.email and signer are not written with the same case.

### ISSUE THREAD

**Issue by AvdP62** [axonivy-market/adobe-acrobat-sign-connector#20]
Failed to retrieve signing url in case the signingUrls.email and in.signer are not written with the same case. Replace .equals with equalsIgnorecase:
https://github.com/axonivy-market/adobe-esign-connector/blob/27357303a856fa96e0466f274c79c7bb24bd4fc3/adobe-esign-connector-demo/src_hd/com/axonivy/connector/adobe/esign/connector/demo/Demo/DemoProcess.p.json#L152

Replacing .equals with .equalsIgnoreCase fixes the issue.
Goes for signer1 and signer2

**Comment by nqhoan-axonivy** [comment]
Thank @AvdP62 for your feedback!
I created a Jira issue to track and adapt it https://1ivy.atlassian.net/browse/MARP-191
We will inform you when the ticket is resolved. Thanks!

**Comment by nqhoan-axonivy** [comment]
HI @AvdP62 we fixed the issue and created a new release 10.0.21 for that enhancement.
Please take it to get the latest feature.
Thanks!
